name    'abiquo-abiquo'
version '0.1.0'
source 'UNKNOWN'
author 'abiquo'
license 'Apache License, Version 2.0'
summary 'UNKNOWN'
description 'UNKNOWN'
project_page 'UNKNOWN'

## Add dependencies, if any:
dependency 'puppetlabs/concat', '>= 1.1.0'
dependency 'puppetlabs/apache', '>= 0.11.0'
dependency 'puppetlabs/stdlib', '>= 4.1.0'
dependency 'puppetlabs/firewall', '>= 1.0.0'
dependency 'jfryman/selinux', '>= 0.2.2'