name    'abiquo-abiquo'
version '0.1.5'
source 'git@github.com:chirauki/abiquo-abiquo.git'
author 'Marc Ciraququi <marc.cirauqui@abiquo.com>'
license 'Apache-2.0'
summary 'Allows to setup basic Abiquo components'
description 'Allows to setup basic Abiquo components'
project_page 'https://github.com/chirauki/abiquo-abiquo'

## Add dependencies, if any:
dependency 'puppetlabs/concat', '>= 1.1.0'
dependency 'puppetlabs/apache', '>= 0.11.0'
dependency 'puppetlabs/stdlib', '>= 4.1.0'
dependency 'puppetlabs/firewall', '>= 1.0.0'
dependency 'jfryman/selinux', '>= 0.2.2'
dependency 'thias/sysctl', '>= 1.0.2'
